const BASE_URL = "http://localhost:42069"

export const LOGIN_ENDPOINT    = BASE_URL + "/login"
export const UPDATE_PENDING_EVENTS_ENDPOINT = BASE_URL + "/eventsUpdate"
export const UPLOAD_ENDPOINT   = BASE_URL + "/upload_files/upload"
export const DOWNLOAD_ENDPOINT = BASE_URL + "/upload_files/download"
export const GET_FEED_ENDPOINT = BASE_URL + "/feed/get"
export const ADD_FRIEND_ENDPOINT = BASE_URL + "/friends/add"
export const CREATE_POST_ENDPOINT = BASE_URL + "/posts/create"
export const COMMENT_ON_POST_ENDPOINT = BASE_URL + "/posts/comment"
export const LIKE_POST_ENDPOINT = BASE_URL + "/posts/like"
export const CREATE_USER_ENDPOINT = BASE_URL + "/users/create"
export const GET_USER_FRIENDS_LIST_ENDPOINT = BASE_URL + "/users/friends"
export const CREATE_EVENT_ENDPOINT = BASE_URL + "/events/create"
export const SHOW_EVENT_INFO_ENDPOINT = BASE_URL + "/events/show"
export const ADD_EVENT_TO_PENDING_ENDPOINT = BASE_URL + "/events/addPending"